### PR TITLE
build: bump gradle to 7.6

### PR DESCRIPTION
**Pull request by yeikel**

### CODE REVIEW

**Comment by timtebeek** [comment]
Hi @yeikel , thanks again for ensuring we use the latest version of the Gradle wrapper! Just so you know: we're looking to automate these Gradle wrapper bumps using our recipes, so we hope these bumps soon won't be necessary anymore.

Quick question: how are you creating these bump pull requests? Because I've seen a few instances where I arrive at slightly different binaries & scripts, as seen in the updated commit https://github.com/openrewrite/rewrite-recipe-bom/pull/13/commits/fea42214a4c6f51f2c54b9be5fdbd8eba143b12b.

For reference: I run `gradle wrapper --gradle-version 7.6` through
```
$ gradle --version

------------------------------------------------------------
Gradle 7.6
------------------------------------------------------------

Build time:   2022-11-25 13:35:10 UTC
Revision:     daece9dbc5b79370cc8e4fd6fe4b2cd400e150a8

Kotlin:       1.7.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.5 (Eclipse Adoptium 17.0.5+8)
OS:           Linux 5.15.0-58-generic amd64
```

**Comment by yeikel** [comment]
> Hi @yeikel , thanks again for ensuring we use the latest version of the Gradle wrapper! Just so you know: we're looking to automate these Gradle wrapper bumps using our recipes, so we hope these bumps soon won't be necessary anymore.
> 
> Quick question: how are you creating these bump pull requests? Because I've seen a few instances where I arrive at slightly different binaries & scripts, as seen in the updated commit https://github.com/openrewrite/rewrite-recipe-bom/pull/13/commits/fea42214a4c6f51f2c54b9be5fdbd8eba143b12b.
> 
> For reference: I run `gradle wrapper --gradle-version 7.6` through
> ```
> $ gradle --version
> 
> ------------------------------------------------------------
> Gradle 7.6
> ------------------------------------------------------------
> 
> Build time:   2022-11-25 13:35:10 UTC
> Revision:     daece9dbc5b79370cc8e4fd6fe4b2cd400e150a8
> 
> Kotlin:       1.7.10
> Groovy:       3.0.13
> Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
> JVM:          17.0.5 (Eclipse Adoptium 17.0.5+8)
> OS:           Linux 5.15.0-58-generic amd64
> ```

I am running the same but from a Windows machine

**Comment by timtebeek** [comment]
That's odd; No real issue as I expect us to move to automating these shortly; perhaps we can hold off on any further wrapper bumps until then? Thanks for these last few though! Good to be aware of what we're using and where.

**Comment by yeikel** [comment]
> That's odd; No real issue as I expect us to move to automating these shortly; perhaps we can hold off on any further wrapper bumps until then? Thanks for these last few though! Good to be aware of what we're using and where.

Maybe it is because my local gradle version is behind

> 
> C:\Users\Yeikel>gradle --version
> 
> ------------------------------------------------------------
> Gradle 7.4.2
> ------------------------------------------------------------
> 
> Build time:   2022-03-31 15:25:29 UTC
> Revision:     540473b8118064efcc264694cbcaa4b677f61041
> 
> Kotlin:       1.5.31
> Groovy:       3.0.9
> Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
> JVM:          11.0.12 (Oracle Corporation 11.0.12+7)
> OS:           Windows 10 10.0 amd64

**Comment by timtebeek** [comment]
Ah yes, an outdated Gradle version will have an effect on the gradle wrapper files it produces I believe; there's a few comments like that on some of the Gradle wrapper issues on our backlog. That's also where I expect the Gradle 8 fixes will go, so fingers crossed these are the last of the manual bumps. Thanks again!

**Pull request merged**
